
export const CREATE_TEAM = 'CREATE_TEAM'
export const SELECT_QUESTION = 'SELECT_QUESTION'
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const ADD_POINT = 'ADD_POINT'
export const REMOVE_POINT = 'REMOVE_POINT'
export const FETCH_QUESTION = 'FETCH_QUESTION'
export const REMOVE_QUESTION = 'REMOVE_QUESTION'