
export const CREATE_TEAM = 'CREATE_TEAM'
export const ADD_POINT = 'ADD_POINT'
export const REMOVE_POINT = 'REMOVE_POINT'
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const FETCH_QUESTION = 'FETCH_QUESTION'
export const NEXT_QUESTION = 'NEXT_QUESTION'
export const QUESTIONS_START = 'QUESTIONS_START'
export const SET_QUESTIONS = "SET_QUESTIONS"
export const FINISH_GAME = "FINISH_GAME"
export const UNSET_QUESTION = 'UNSET_QUESTION'